name: build

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        dotnet: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # tag=v2.1.0
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Add GitHub NuGet registry
        run: dotnet nuget update source github --username JamieMagee --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore --nologo
      - name: Test
        run: dotnet test --no-restore --verbosity normal --nologo
      - name: Publish
        run: dotnet publish src/Hoist --configuration Release --output artifact
      - name: Upload
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: ${{matrix.os}}
          path: ./artifact