name: build

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        dotnet: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Add GitHub NuGet registry
        run: dotnet nuget update source github --username JamieMagee --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore --nologo
      - name: Test
        run: dotnet test --no-restore --verbosity normal --nologo
      - name: Publish
        run: dotnet publish src/Hoist --configuration Release --output artifact
      - name: Upload
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3
        with:
          name: ${{matrix.os}}
          path: ./artifact